#!/bin/bash -x
# mount the root partition and fetch the git hash
# parameter 1 - partition of rootfs

if [ $# -eq 0 ]; then
   echo "Usage: $0 directory of root-fs
   exit 1
fi

mount $PARTITION /mnt
pushd /mnt/opt/schoolserver/xsce
HASH=`git log --pretty=format:'g%h' -n 1`
popd 
umount /mnt

# save this filename for later use
mount /dev/sdb2 /mnt
echo $HASH > /mnt/last-iiab-hash
umount /mnt

