#!/bin/bash -x
# mount the root partition and fetch the git hash
# parameter 1 - partition of rootfs

# assume that we can write into the current directory

if [ $# -eq 0 ]; then
   echo "Usage: $0 directory of root-fs
   exit 1
fi

mkdir rootfs
mount $PARTITION rootfs 
pushd rootfs/opt/schoolserver/xsce
HASH=`git log --pretty=format:'g%h' -n 1`
popd 
umount rootfs

# save this filename for later use
echo $HASH > last-iiab-hash

